# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: da30877901c58e44ad83f1707b9a7310304bd37d64e3e9046fbc5632611bb7741413cd7be2d026ce5f107fade6cead99b1e61c51b21e2dceb797b69182c5495a

test:
  secret_key_base: 0ea50fa3e3e9732f3cc11194d320c769516b15c195f207ef54a8ca51fbda97503164a0fa255d7687bed8e3272447aa3ea08ad6c22100b0744f7095f2609f7c89

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
